{
 "cells": [
  {
   "cell_type": "code",
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2025-05-08T14:49:58.923899Z",
     "start_time": "2025-05-08T14:49:29.338938Z"
    }
   },
   "source": "! pip install --upgrade --quiet bitsandbytes datasets peft transformers trl",
   "outputs": [],
   "execution_count": 1
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-05-08T15:16:02.573189Z",
     "start_time": "2025-05-08T15:16:01.515932Z"
    }
   },
   "cell_type": "code",
   "source": [
    "from huggingface_hub import snapshot_download\n",
    "\n",
    "access_token = \"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\"\n",
    "\n",
    "snapshot_download(repo_id=\"google/txgemma-2b-predict\", repo_type=\"model\", token=access_token)"
   ],
   "id": "13e83836bf59dadb",
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]\n"
     ]
    },
    {
     "ename": "LocalEntryNotFoundError",
     "evalue": "An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.",
     "output_type": "error",
     "traceback": [
      "\u001B[31m---------------------------------------------------------------------------\u001B[39m",
      "\u001B[31mHTTPError\u001B[39m                                 Traceback (most recent call last)",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_http.py:409\u001B[39m, in \u001B[36mhf_raise_for_status\u001B[39m\u001B[34m(response, endpoint_name)\u001B[39m\n\u001B[32m    408\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m--> \u001B[39m\u001B[32m409\u001B[39m     response.raise_for_status()\n\u001B[32m    410\u001B[39m \u001B[38;5;28;01mexcept\u001B[39;00m HTTPError \u001B[38;5;28;01mas\u001B[39;00m e:\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\requests\\models.py:1024\u001B[39m, in \u001B[36mResponse.raise_for_status\u001B[39m\u001B[34m(self)\u001B[39m\n\u001B[32m   1023\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m http_error_msg:\n\u001B[32m-> \u001B[39m\u001B[32m1024\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m HTTPError(http_error_msg, response=\u001B[38;5;28mself\u001B[39m)\n",
      "\u001B[31mHTTPError\u001B[39m: 403 Client Error: Forbidden for url: https://huggingface.co/google/txgemma-2b-predict/resolve/6b0eb81135ad9e73c9c18409c03e315a5a23a18f/.gitattributes",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001B[31mHfHubHTTPError\u001B[39m                            Traceback (most recent call last)",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1531\u001B[39m, in \u001B[36m_get_metadata_or_catch_error\u001B[39m\u001B[34m(repo_id, filename, repo_type, revision, endpoint, proxies, etag_timeout, headers, token, local_files_only, relative_filename, storage_folder)\u001B[39m\n\u001B[32m   1530\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m-> \u001B[39m\u001B[32m1531\u001B[39m     metadata = get_hf_file_metadata(\n\u001B[32m   1532\u001B[39m         url=url, proxies=proxies, timeout=etag_timeout, headers=headers, token=token\n\u001B[32m   1533\u001B[39m     )\n\u001B[32m   1534\u001B[39m \u001B[38;5;28;01mexcept\u001B[39;00m EntryNotFoundError \u001B[38;5;28;01mas\u001B[39;00m http_error:\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_validators.py:114\u001B[39m, in \u001B[36mvalidate_hf_hub_args.<locals>._inner_fn\u001B[39m\u001B[34m(*args, **kwargs)\u001B[39m\n\u001B[32m    112\u001B[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001B[34m__name__\u001B[39m, has_token=has_token, kwargs=kwargs)\n\u001B[32m--> \u001B[39m\u001B[32m114\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m fn(*args, **kwargs)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1448\u001B[39m, in \u001B[36mget_hf_file_metadata\u001B[39m\u001B[34m(url, token, proxies, timeout, library_name, library_version, user_agent, headers)\u001B[39m\n\u001B[32m   1447\u001B[39m \u001B[38;5;66;03m# Retrieve metadata\u001B[39;00m\n\u001B[32m-> \u001B[39m\u001B[32m1448\u001B[39m r = _request_wrapper(\n\u001B[32m   1449\u001B[39m     method=\u001B[33m\"\u001B[39m\u001B[33mHEAD\u001B[39m\u001B[33m\"\u001B[39m,\n\u001B[32m   1450\u001B[39m     url=url,\n\u001B[32m   1451\u001B[39m     headers=hf_headers,\n\u001B[32m   1452\u001B[39m     allow_redirects=\u001B[38;5;28;01mFalse\u001B[39;00m,\n\u001B[32m   1453\u001B[39m     follow_relative_redirects=\u001B[38;5;28;01mTrue\u001B[39;00m,\n\u001B[32m   1454\u001B[39m     proxies=proxies,\n\u001B[32m   1455\u001B[39m     timeout=timeout,\n\u001B[32m   1456\u001B[39m )\n\u001B[32m   1457\u001B[39m hf_raise_for_status(r)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:286\u001B[39m, in \u001B[36m_request_wrapper\u001B[39m\u001B[34m(method, url, follow_relative_redirects, **params)\u001B[39m\n\u001B[32m    285\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m follow_relative_redirects:\n\u001B[32m--> \u001B[39m\u001B[32m286\u001B[39m     response = _request_wrapper(\n\u001B[32m    287\u001B[39m         method=method,\n\u001B[32m    288\u001B[39m         url=url,\n\u001B[32m    289\u001B[39m         follow_relative_redirects=\u001B[38;5;28;01mFalse\u001B[39;00m,\n\u001B[32m    290\u001B[39m         **params,\n\u001B[32m    291\u001B[39m     )\n\u001B[32m    293\u001B[39m     \u001B[38;5;66;03m# If redirection, we redirect only relative paths.\u001B[39;00m\n\u001B[32m    294\u001B[39m     \u001B[38;5;66;03m# This is useful in case of a renamed repository.\u001B[39;00m\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:310\u001B[39m, in \u001B[36m_request_wrapper\u001B[39m\u001B[34m(method, url, follow_relative_redirects, **params)\u001B[39m\n\u001B[32m    309\u001B[39m response = http_backoff(method=method, url=url, **params, retry_on_exceptions=(), retry_on_status_codes=(\u001B[32m429\u001B[39m,))\n\u001B[32m--> \u001B[39m\u001B[32m310\u001B[39m hf_raise_for_status(response)\n\u001B[32m    311\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m response\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_http.py:473\u001B[39m, in \u001B[36mhf_raise_for_status\u001B[39m\u001B[34m(response, endpoint_name)\u001B[39m\n\u001B[32m    468\u001B[39m     message = (\n\u001B[32m    469\u001B[39m         \u001B[33mf\u001B[39m\u001B[33m\"\u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[38;5;132;01m{\u001B[39;00mresponse.status_code\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m Forbidden: \u001B[39m\u001B[38;5;132;01m{\u001B[39;00merror_message\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    470\u001B[39m         + \u001B[33mf\u001B[39m\u001B[33m\"\u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mCannot access content at: \u001B[39m\u001B[38;5;132;01m{\u001B[39;00mresponse.url\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    471\u001B[39m         + \u001B[33m\"\u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mMake sure your token has the correct permissions.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    472\u001B[39m     )\n\u001B[32m--> \u001B[39m\u001B[32m473\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m _format(HfHubHTTPError, message, response) \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34;01me\u001B[39;00m\n\u001B[32m    475\u001B[39m \u001B[38;5;28;01melif\u001B[39;00m response.status_code == \u001B[32m416\u001B[39m:\n",
      "\u001B[31mHfHubHTTPError\u001B[39m: (Request ID: Root=1-681ccab2-74ac271750ad9ea3419a6252;71a7932a-18d2-47ac-84ac-ed6849458a72)\n\n403 Forbidden: Please enable access to public gated repositories in your fine-grained token settings to view this repository..\nCannot access content at: https://huggingface.co/google/txgemma-2b-predict/resolve/6b0eb81135ad9e73c9c18409c03e315a5a23a18f/.gitattributes.\nMake sure your token has the correct permissions.",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001B[31mLocalEntryNotFoundError\u001B[39m                   Traceback (most recent call last)",
      "\u001B[36mCell\u001B[39m\u001B[36m \u001B[39m\u001B[32mIn[6]\u001B[39m\u001B[32m, line 5\u001B[39m\n\u001B[32m      1\u001B[39m \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34;01mhuggingface_hub\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[38;5;28;01mimport\u001B[39;00m snapshot_download\n\u001B[32m      3\u001B[39m access_token = \u001B[33m\"\u001B[39m\u001B[33mhf_xbeQVfwEWGtcTSgRDNdAqpjdUXzSUWtITy\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m----> \u001B[39m\u001B[32m5\u001B[39m snapshot_download(repo_id=\u001B[33m\"\u001B[39m\u001B[33mgoogle/txgemma-2b-predict\u001B[39m\u001B[33m\"\u001B[39m, repo_type=\u001B[33m\"\u001B[39m\u001B[33mmodel\u001B[39m\u001B[33m\"\u001B[39m, token=access_token)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_validators.py:114\u001B[39m, in \u001B[36mvalidate_hf_hub_args.<locals>._inner_fn\u001B[39m\u001B[34m(*args, **kwargs)\u001B[39m\n\u001B[32m    111\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m check_use_auth_token:\n\u001B[32m    112\u001B[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001B[34m__name__\u001B[39m, has_token=has_token, kwargs=kwargs)\n\u001B[32m--> \u001B[39m\u001B[32m114\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m fn(*args, **kwargs)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\_snapshot_download.py:297\u001B[39m, in \u001B[36msnapshot_download\u001B[39m\u001B[34m(repo_id, repo_type, revision, cache_dir, local_dir, library_name, library_version, user_agent, proxies, etag_timeout, force_download, token, local_files_only, allow_patterns, ignore_patterns, max_workers, tqdm_class, headers, endpoint, local_dir_use_symlinks, resume_download)\u001B[39m\n\u001B[32m    295\u001B[39m         _inner_hf_hub_download(file)\n\u001B[32m    296\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m--> \u001B[39m\u001B[32m297\u001B[39m     thread_map(\n\u001B[32m    298\u001B[39m         _inner_hf_hub_download,\n\u001B[32m    299\u001B[39m         filtered_repo_files,\n\u001B[32m    300\u001B[39m         desc=\u001B[33mf\u001B[39m\u001B[33m\"\u001B[39m\u001B[33mFetching \u001B[39m\u001B[38;5;132;01m{\u001B[39;00m\u001B[38;5;28mlen\u001B[39m(filtered_repo_files)\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m files\u001B[39m\u001B[33m\"\u001B[39m,\n\u001B[32m    301\u001B[39m         max_workers=max_workers,\n\u001B[32m    302\u001B[39m         \u001B[38;5;66;03m# User can use its own tqdm class or the default one from `huggingface_hub.utils`\u001B[39;00m\n\u001B[32m    303\u001B[39m         tqdm_class=tqdm_class \u001B[38;5;129;01mor\u001B[39;00m hf_tqdm,\n\u001B[32m    304\u001B[39m     )\n\u001B[32m    306\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m local_dir \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;129;01mnot\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m:\n\u001B[32m    307\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28mstr\u001B[39m(os.path.realpath(local_dir))\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\tqdm\\contrib\\concurrent.py:69\u001B[39m, in \u001B[36mthread_map\u001B[39m\u001B[34m(fn, *iterables, **tqdm_kwargs)\u001B[39m\n\u001B[32m     55\u001B[39m \u001B[38;5;250m\u001B[39m\u001B[33;03m\"\"\"\u001B[39;00m\n\u001B[32m     56\u001B[39m \u001B[33;03mEquivalent of `list(map(fn, *iterables))`\u001B[39;00m\n\u001B[32m     57\u001B[39m \u001B[33;03mdriven by `concurrent.futures.ThreadPoolExecutor`.\u001B[39;00m\n\u001B[32m   (...)\u001B[39m\u001B[32m     66\u001B[39m \u001B[33;03m    [default: max(32, cpu_count() + 4)].\u001B[39;00m\n\u001B[32m     67\u001B[39m \u001B[33;03m\"\"\"\u001B[39;00m\n\u001B[32m     68\u001B[39m \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34;01mconcurrent\u001B[39;00m\u001B[34;01m.\u001B[39;00m\u001B[34;01mfutures\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[38;5;28;01mimport\u001B[39;00m ThreadPoolExecutor\n\u001B[32m---> \u001B[39m\u001B[32m69\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\tqdm\\contrib\\concurrent.py:51\u001B[39m, in \u001B[36m_executor_map\u001B[39m\u001B[34m(PoolExecutor, fn, *iterables, **tqdm_kwargs)\u001B[39m\n\u001B[32m     47\u001B[39m \u001B[38;5;28;01mwith\u001B[39;00m ensure_lock(tqdm_class, lock_name=lock_name) \u001B[38;5;28;01mas\u001B[39;00m lk:\n\u001B[32m     48\u001B[39m     \u001B[38;5;66;03m# share lock in case workers are already using `tqdm`\u001B[39;00m\n\u001B[32m     49\u001B[39m     \u001B[38;5;28;01mwith\u001B[39;00m PoolExecutor(max_workers=max_workers, initializer=tqdm_class.set_lock,\n\u001B[32m     50\u001B[39m                       initargs=(lk,)) \u001B[38;5;28;01mas\u001B[39;00m ex:\n\u001B[32m---> \u001B[39m\u001B[32m51\u001B[39m         \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28mlist\u001B[39m(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\tqdm\\std.py:1181\u001B[39m, in \u001B[36mtqdm.__iter__\u001B[39m\u001B[34m(self)\u001B[39m\n\u001B[32m   1178\u001B[39m time = \u001B[38;5;28mself\u001B[39m._time\n\u001B[32m   1180\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m-> \u001B[39m\u001B[32m1181\u001B[39m     \u001B[38;5;28;01mfor\u001B[39;00m obj \u001B[38;5;129;01min\u001B[39;00m iterable:\n\u001B[32m   1182\u001B[39m         \u001B[38;5;28;01myield\u001B[39;00m obj\n\u001B[32m   1183\u001B[39m         \u001B[38;5;66;03m# Update and possibly print the progressbar.\u001B[39;00m\n\u001B[32m   1184\u001B[39m         \u001B[38;5;66;03m# Note: does not call self.update(1) for speed optimisation.\u001B[39;00m\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\concurrent\\futures\\_base.py:619\u001B[39m, in \u001B[36mExecutor.map.<locals>.result_iterator\u001B[39m\u001B[34m()\u001B[39m\n\u001B[32m    616\u001B[39m \u001B[38;5;28;01mwhile\u001B[39;00m fs:\n\u001B[32m    617\u001B[39m     \u001B[38;5;66;03m# Careful not to keep a reference to the popped future\u001B[39;00m\n\u001B[32m    618\u001B[39m     \u001B[38;5;28;01mif\u001B[39;00m timeout \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m:\n\u001B[32m--> \u001B[39m\u001B[32m619\u001B[39m         \u001B[38;5;28;01myield\u001B[39;00m _result_or_cancel(fs.pop())\n\u001B[32m    620\u001B[39m     \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m    621\u001B[39m         \u001B[38;5;28;01myield\u001B[39;00m _result_or_cancel(fs.pop(), end_time - time.monotonic())\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\concurrent\\futures\\_base.py:317\u001B[39m, in \u001B[36m_result_or_cancel\u001B[39m\u001B[34m(***failed resolving arguments***)\u001B[39m\n\u001B[32m    315\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m    316\u001B[39m     \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m--> \u001B[39m\u001B[32m317\u001B[39m         \u001B[38;5;28;01mreturn\u001B[39;00m fut.result(timeout)\n\u001B[32m    318\u001B[39m     \u001B[38;5;28;01mfinally\u001B[39;00m:\n\u001B[32m    319\u001B[39m         fut.cancel()\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\concurrent\\futures\\_base.py:456\u001B[39m, in \u001B[36mFuture.result\u001B[39m\u001B[34m(self, timeout)\u001B[39m\n\u001B[32m    454\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m CancelledError()\n\u001B[32m    455\u001B[39m \u001B[38;5;28;01melif\u001B[39;00m \u001B[38;5;28mself\u001B[39m._state == FINISHED:\n\u001B[32m--> \u001B[39m\u001B[32m456\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28mself\u001B[39m.__get_result()\n\u001B[32m    457\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m    458\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m \u001B[38;5;167;01mTimeoutError\u001B[39;00m()\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\concurrent\\futures\\_base.py:401\u001B[39m, in \u001B[36mFuture.__get_result\u001B[39m\u001B[34m(self)\u001B[39m\n\u001B[32m    399\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28mself\u001B[39m._exception:\n\u001B[32m    400\u001B[39m     \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m--> \u001B[39m\u001B[32m401\u001B[39m         \u001B[38;5;28;01mraise\u001B[39;00m \u001B[38;5;28mself\u001B[39m._exception\n\u001B[32m    402\u001B[39m     \u001B[38;5;28;01mfinally\u001B[39;00m:\n\u001B[32m    403\u001B[39m         \u001B[38;5;66;03m# Break a reference cycle with the exception in self._exception\u001B[39;00m\n\u001B[32m    404\u001B[39m         \u001B[38;5;28mself\u001B[39m = \u001B[38;5;28;01mNone\u001B[39;00m\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\concurrent\\futures\\thread.py:59\u001B[39m, in \u001B[36m_WorkItem.run\u001B[39m\u001B[34m(self)\u001B[39m\n\u001B[32m     56\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m\n\u001B[32m     58\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m---> \u001B[39m\u001B[32m59\u001B[39m     result = \u001B[38;5;28mself\u001B[39m.fn(*\u001B[38;5;28mself\u001B[39m.args, **\u001B[38;5;28mself\u001B[39m.kwargs)\n\u001B[32m     60\u001B[39m \u001B[38;5;28;01mexcept\u001B[39;00m \u001B[38;5;167;01mBaseException\u001B[39;00m \u001B[38;5;28;01mas\u001B[39;00m exc:\n\u001B[32m     61\u001B[39m     \u001B[38;5;28mself\u001B[39m.future.set_exception(exc)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\_snapshot_download.py:271\u001B[39m, in \u001B[36msnapshot_download.<locals>._inner_hf_hub_download\u001B[39m\u001B[34m(repo_file)\u001B[39m\n\u001B[32m    270\u001B[39m \u001B[38;5;28;01mdef\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34m_inner_hf_hub_download\u001B[39m(repo_file: \u001B[38;5;28mstr\u001B[39m):\n\u001B[32m--> \u001B[39m\u001B[32m271\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m hf_hub_download(\n\u001B[32m    272\u001B[39m         repo_id,\n\u001B[32m    273\u001B[39m         filename=repo_file,\n\u001B[32m    274\u001B[39m         repo_type=repo_type,\n\u001B[32m    275\u001B[39m         revision=commit_hash,\n\u001B[32m    276\u001B[39m         endpoint=endpoint,\n\u001B[32m    277\u001B[39m         cache_dir=cache_dir,\n\u001B[32m    278\u001B[39m         local_dir=local_dir,\n\u001B[32m    279\u001B[39m         local_dir_use_symlinks=local_dir_use_symlinks,\n\u001B[32m    280\u001B[39m         library_name=library_name,\n\u001B[32m    281\u001B[39m         library_version=library_version,\n\u001B[32m    282\u001B[39m         user_agent=user_agent,\n\u001B[32m    283\u001B[39m         proxies=proxies,\n\u001B[32m    284\u001B[39m         etag_timeout=etag_timeout,\n\u001B[32m    285\u001B[39m         resume_download=resume_download,\n\u001B[32m    286\u001B[39m         force_download=force_download,\n\u001B[32m    287\u001B[39m         token=token,\n\u001B[32m    288\u001B[39m         headers=headers,\n\u001B[32m    289\u001B[39m     )\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_validators.py:114\u001B[39m, in \u001B[36mvalidate_hf_hub_args.<locals>._inner_fn\u001B[39m\u001B[34m(*args, **kwargs)\u001B[39m\n\u001B[32m    111\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m check_use_auth_token:\n\u001B[32m    112\u001B[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001B[34m__name__\u001B[39m, has_token=has_token, kwargs=kwargs)\n\u001B[32m--> \u001B[39m\u001B[32m114\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m fn(*args, **kwargs)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1008\u001B[39m, in \u001B[36mhf_hub_download\u001B[39m\u001B[34m(repo_id, filename, subfolder, repo_type, revision, library_name, library_version, cache_dir, local_dir, user_agent, force_download, proxies, etag_timeout, token, local_files_only, headers, endpoint, resume_download, force_filename, local_dir_use_symlinks)\u001B[39m\n\u001B[32m    988\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m _hf_hub_download_to_local_dir(\n\u001B[32m    989\u001B[39m         \u001B[38;5;66;03m# Destination\u001B[39;00m\n\u001B[32m    990\u001B[39m         local_dir=local_dir,\n\u001B[32m   (...)\u001B[39m\u001B[32m   1005\u001B[39m         local_files_only=local_files_only,\n\u001B[32m   1006\u001B[39m     )\n\u001B[32m   1007\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m-> \u001B[39m\u001B[32m1008\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m _hf_hub_download_to_cache_dir(\n\u001B[32m   1009\u001B[39m         \u001B[38;5;66;03m# Destination\u001B[39;00m\n\u001B[32m   1010\u001B[39m         cache_dir=cache_dir,\n\u001B[32m   1011\u001B[39m         \u001B[38;5;66;03m# File info\u001B[39;00m\n\u001B[32m   1012\u001B[39m         repo_id=repo_id,\n\u001B[32m   1013\u001B[39m         filename=filename,\n\u001B[32m   1014\u001B[39m         repo_type=repo_type,\n\u001B[32m   1015\u001B[39m         revision=revision,\n\u001B[32m   1016\u001B[39m         \u001B[38;5;66;03m# HTTP info\u001B[39;00m\n\u001B[32m   1017\u001B[39m         endpoint=endpoint,\n\u001B[32m   1018\u001B[39m         etag_timeout=etag_timeout,\n\u001B[32m   1019\u001B[39m         headers=hf_headers,\n\u001B[32m   1020\u001B[39m         proxies=proxies,\n\u001B[32m   1021\u001B[39m         token=token,\n\u001B[32m   1022\u001B[39m         \u001B[38;5;66;03m# Additional options\u001B[39;00m\n\u001B[32m   1023\u001B[39m         local_files_only=local_files_only,\n\u001B[32m   1024\u001B[39m         force_download=force_download,\n\u001B[32m   1025\u001B[39m     )\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1115\u001B[39m, in \u001B[36m_hf_hub_download_to_cache_dir\u001B[39m\u001B[34m(cache_dir, repo_id, filename, repo_type, revision, endpoint, etag_timeout, headers, proxies, token, local_files_only, force_download)\u001B[39m\n\u001B[32m   1112\u001B[39m                 \u001B[38;5;28;01mreturn\u001B[39;00m pointer_path\n\u001B[32m   1114\u001B[39m     \u001B[38;5;66;03m# Otherwise, raise appropriate error\u001B[39;00m\n\u001B[32m-> \u001B[39m\u001B[32m1115\u001B[39m     _raise_on_head_call_error(head_call_error, force_download, local_files_only)\n\u001B[32m   1117\u001B[39m \u001B[38;5;66;03m# From now on, etag, commit_hash, url and size are not None.\u001B[39;00m\n\u001B[32m   1118\u001B[39m \u001B[38;5;28;01massert\u001B[39;00m etag \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;129;01mnot\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m, \u001B[33m\"\u001B[39m\u001B[33metag must have been retrieved from server\u001B[39m\u001B[33m\"\u001B[39m\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1646\u001B[39m, in \u001B[36m_raise_on_head_call_error\u001B[39m\u001B[34m(head_call_error, force_download, local_files_only)\u001B[39m\n\u001B[32m   1643\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m head_call_error\n\u001B[32m   1644\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m   1645\u001B[39m     \u001B[38;5;66;03m# Otherwise: most likely a connection issue or Hub downtime => let's warn the user\u001B[39;00m\n\u001B[32m-> \u001B[39m\u001B[32m1646\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m LocalEntryNotFoundError(\n\u001B[32m   1647\u001B[39m         \u001B[33m\"\u001B[39m\u001B[33mAn error happened while trying to locate the file on the Hub and we cannot find the requested files\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m   1648\u001B[39m         \u001B[33m\"\u001B[39m\u001B[33m in the local cache. Please check your connection and try again or make sure your Internet connection\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m   1649\u001B[39m         \u001B[33m\"\u001B[39m\u001B[33m is on.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m   1650\u001B[39m     ) \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34;01mhead_call_error\u001B[39;00m\n",
      "\u001B[31mLocalEntryNotFoundError\u001B[39m: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on."
     ]
    }
   ],
   "execution_count": 6
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-05-08T15:10:03.340435Z",
     "start_time": "2025-05-08T15:10:02.533993Z"
    }
   },
   "cell_type": "code",
   "source": [
    "import torch\n",
    "from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig\n",
    "\n",
    "model_id = \"google/txgemma-2b-predict\"\n",
    "\n",
    "# Use 4-bit quantization to reduce memory usage\n",
    "quantization_config = BitsAndBytesConfig(\n",
    "    load_in_4bit=True,\n",
    "    bnb_4bit_quant_type=\"nf4\",\n",
    "    bnb_4bit_compute_dtype=torch.bfloat16,\n",
    ")\n",
    "\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_id)\n",
    "model = AutoModelForCausalLM.from_pretrained(\n",
    "    model_id,\n",
    "    quantization_config=quantization_config,\n",
    "    device_map={\"\":0},\n",
    "    torch_dtype=\"auto\",\n",
    "    attn_implementation=\"eager\",\n",
    ")"
   ],
   "id": "bf9efd62c26bc1fd",
   "outputs": [
    {
     "ename": "OSError",
     "evalue": "We couldn't connect to 'https://huggingface.co' to load the files, and couldn't find them in the cached files.\nCheckout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.",
     "output_type": "error",
     "traceback": [
      "\u001B[31m---------------------------------------------------------------------------\u001B[39m",
      "\u001B[31mHTTPError\u001B[39m                                 Traceback (most recent call last)",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_http.py:409\u001B[39m, in \u001B[36mhf_raise_for_status\u001B[39m\u001B[34m(response, endpoint_name)\u001B[39m\n\u001B[32m    408\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m--> \u001B[39m\u001B[32m409\u001B[39m     response.raise_for_status()\n\u001B[32m    410\u001B[39m \u001B[38;5;28;01mexcept\u001B[39;00m HTTPError \u001B[38;5;28;01mas\u001B[39;00m e:\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\requests\\models.py:1024\u001B[39m, in \u001B[36mResponse.raise_for_status\u001B[39m\u001B[34m(self)\u001B[39m\n\u001B[32m   1023\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m http_error_msg:\n\u001B[32m-> \u001B[39m\u001B[32m1024\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m HTTPError(http_error_msg, response=\u001B[38;5;28mself\u001B[39m)\n",
      "\u001B[31mHTTPError\u001B[39m: 403 Client Error: Forbidden for url: https://huggingface.co/google/txgemma-2b-predict/resolve/main/config.json",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001B[31mHfHubHTTPError\u001B[39m                            Traceback (most recent call last)",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1531\u001B[39m, in \u001B[36m_get_metadata_or_catch_error\u001B[39m\u001B[34m(repo_id, filename, repo_type, revision, endpoint, proxies, etag_timeout, headers, token, local_files_only, relative_filename, storage_folder)\u001B[39m\n\u001B[32m   1530\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m-> \u001B[39m\u001B[32m1531\u001B[39m     metadata = get_hf_file_metadata(\n\u001B[32m   1532\u001B[39m         url=url, proxies=proxies, timeout=etag_timeout, headers=headers, token=token\n\u001B[32m   1533\u001B[39m     )\n\u001B[32m   1534\u001B[39m \u001B[38;5;28;01mexcept\u001B[39;00m EntryNotFoundError \u001B[38;5;28;01mas\u001B[39;00m http_error:\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_validators.py:114\u001B[39m, in \u001B[36mvalidate_hf_hub_args.<locals>._inner_fn\u001B[39m\u001B[34m(*args, **kwargs)\u001B[39m\n\u001B[32m    112\u001B[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001B[34m__name__\u001B[39m, has_token=has_token, kwargs=kwargs)\n\u001B[32m--> \u001B[39m\u001B[32m114\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m fn(*args, **kwargs)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1448\u001B[39m, in \u001B[36mget_hf_file_metadata\u001B[39m\u001B[34m(url, token, proxies, timeout, library_name, library_version, user_agent, headers)\u001B[39m\n\u001B[32m   1447\u001B[39m \u001B[38;5;66;03m# Retrieve metadata\u001B[39;00m\n\u001B[32m-> \u001B[39m\u001B[32m1448\u001B[39m r = _request_wrapper(\n\u001B[32m   1449\u001B[39m     method=\u001B[33m\"\u001B[39m\u001B[33mHEAD\u001B[39m\u001B[33m\"\u001B[39m,\n\u001B[32m   1450\u001B[39m     url=url,\n\u001B[32m   1451\u001B[39m     headers=hf_headers,\n\u001B[32m   1452\u001B[39m     allow_redirects=\u001B[38;5;28;01mFalse\u001B[39;00m,\n\u001B[32m   1453\u001B[39m     follow_relative_redirects=\u001B[38;5;28;01mTrue\u001B[39;00m,\n\u001B[32m   1454\u001B[39m     proxies=proxies,\n\u001B[32m   1455\u001B[39m     timeout=timeout,\n\u001B[32m   1456\u001B[39m )\n\u001B[32m   1457\u001B[39m hf_raise_for_status(r)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:286\u001B[39m, in \u001B[36m_request_wrapper\u001B[39m\u001B[34m(method, url, follow_relative_redirects, **params)\u001B[39m\n\u001B[32m    285\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m follow_relative_redirects:\n\u001B[32m--> \u001B[39m\u001B[32m286\u001B[39m     response = _request_wrapper(\n\u001B[32m    287\u001B[39m         method=method,\n\u001B[32m    288\u001B[39m         url=url,\n\u001B[32m    289\u001B[39m         follow_relative_redirects=\u001B[38;5;28;01mFalse\u001B[39;00m,\n\u001B[32m    290\u001B[39m         **params,\n\u001B[32m    291\u001B[39m     )\n\u001B[32m    293\u001B[39m     \u001B[38;5;66;03m# If redirection, we redirect only relative paths.\u001B[39;00m\n\u001B[32m    294\u001B[39m     \u001B[38;5;66;03m# This is useful in case of a renamed repository.\u001B[39;00m\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:310\u001B[39m, in \u001B[36m_request_wrapper\u001B[39m\u001B[34m(method, url, follow_relative_redirects, **params)\u001B[39m\n\u001B[32m    309\u001B[39m response = http_backoff(method=method, url=url, **params, retry_on_exceptions=(), retry_on_status_codes=(\u001B[32m429\u001B[39m,))\n\u001B[32m--> \u001B[39m\u001B[32m310\u001B[39m hf_raise_for_status(response)\n\u001B[32m    311\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m response\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_http.py:473\u001B[39m, in \u001B[36mhf_raise_for_status\u001B[39m\u001B[34m(response, endpoint_name)\u001B[39m\n\u001B[32m    468\u001B[39m     message = (\n\u001B[32m    469\u001B[39m         \u001B[33mf\u001B[39m\u001B[33m\"\u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[38;5;132;01m{\u001B[39;00mresponse.status_code\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m Forbidden: \u001B[39m\u001B[38;5;132;01m{\u001B[39;00merror_message\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    470\u001B[39m         + \u001B[33mf\u001B[39m\u001B[33m\"\u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mCannot access content at: \u001B[39m\u001B[38;5;132;01m{\u001B[39;00mresponse.url\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    471\u001B[39m         + \u001B[33m\"\u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mMake sure your token has the correct permissions.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    472\u001B[39m     )\n\u001B[32m--> \u001B[39m\u001B[32m473\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m _format(HfHubHTTPError, message, response) \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34;01me\u001B[39;00m\n\u001B[32m    475\u001B[39m \u001B[38;5;28;01melif\u001B[39;00m response.status_code == \u001B[32m416\u001B[39m:\n",
      "\u001B[31mHfHubHTTPError\u001B[39m: (Request ID: Root=1-681cc94b-171edcca74e280c164d67196;01924173-8e62-4bd1-be07-e855b384fb01)\n\n403 Forbidden: Please enable access to public gated repositories in your fine-grained token settings to view this repository..\nCannot access content at: https://huggingface.co/google/txgemma-2b-predict/resolve/main/config.json.\nMake sure your token has the correct permissions.",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001B[31mLocalEntryNotFoundError\u001B[39m                   Traceback (most recent call last)",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\transformers\\utils\\hub.py:424\u001B[39m, in \u001B[36mcached_files\u001B[39m\u001B[34m(path_or_repo_id, filenames, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)\u001B[39m\n\u001B[32m    422\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28mlen\u001B[39m(full_filenames) == \u001B[32m1\u001B[39m:\n\u001B[32m    423\u001B[39m     \u001B[38;5;66;03m# This is slightly better for only 1 file\u001B[39;00m\n\u001B[32m--> \u001B[39m\u001B[32m424\u001B[39m     hf_hub_download(\n\u001B[32m    425\u001B[39m         path_or_repo_id,\n\u001B[32m    426\u001B[39m         filenames[\u001B[32m0\u001B[39m],\n\u001B[32m    427\u001B[39m         subfolder=\u001B[38;5;28;01mNone\u001B[39;00m \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28mlen\u001B[39m(subfolder) == \u001B[32m0\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m subfolder,\n\u001B[32m    428\u001B[39m         repo_type=repo_type,\n\u001B[32m    429\u001B[39m         revision=revision,\n\u001B[32m    430\u001B[39m         cache_dir=cache_dir,\n\u001B[32m    431\u001B[39m         user_agent=user_agent,\n\u001B[32m    432\u001B[39m         force_download=force_download,\n\u001B[32m    433\u001B[39m         proxies=proxies,\n\u001B[32m    434\u001B[39m         resume_download=resume_download,\n\u001B[32m    435\u001B[39m         token=token,\n\u001B[32m    436\u001B[39m         local_files_only=local_files_only,\n\u001B[32m    437\u001B[39m     )\n\u001B[32m    438\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m:\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\utils\\_validators.py:114\u001B[39m, in \u001B[36mvalidate_hf_hub_args.<locals>._inner_fn\u001B[39m\u001B[34m(*args, **kwargs)\u001B[39m\n\u001B[32m    112\u001B[39m     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.\u001B[34m__name__\u001B[39m, has_token=has_token, kwargs=kwargs)\n\u001B[32m--> \u001B[39m\u001B[32m114\u001B[39m \u001B[38;5;28;01mreturn\u001B[39;00m fn(*args, **kwargs)\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1008\u001B[39m, in \u001B[36mhf_hub_download\u001B[39m\u001B[34m(repo_id, filename, subfolder, repo_type, revision, library_name, library_version, cache_dir, local_dir, user_agent, force_download, proxies, etag_timeout, token, local_files_only, headers, endpoint, resume_download, force_filename, local_dir_use_symlinks)\u001B[39m\n\u001B[32m   1007\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m-> \u001B[39m\u001B[32m1008\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m _hf_hub_download_to_cache_dir(\n\u001B[32m   1009\u001B[39m         \u001B[38;5;66;03m# Destination\u001B[39;00m\n\u001B[32m   1010\u001B[39m         cache_dir=cache_dir,\n\u001B[32m   1011\u001B[39m         \u001B[38;5;66;03m# File info\u001B[39;00m\n\u001B[32m   1012\u001B[39m         repo_id=repo_id,\n\u001B[32m   1013\u001B[39m         filename=filename,\n\u001B[32m   1014\u001B[39m         repo_type=repo_type,\n\u001B[32m   1015\u001B[39m         revision=revision,\n\u001B[32m   1016\u001B[39m         \u001B[38;5;66;03m# HTTP info\u001B[39;00m\n\u001B[32m   1017\u001B[39m         endpoint=endpoint,\n\u001B[32m   1018\u001B[39m         etag_timeout=etag_timeout,\n\u001B[32m   1019\u001B[39m         headers=hf_headers,\n\u001B[32m   1020\u001B[39m         proxies=proxies,\n\u001B[32m   1021\u001B[39m         token=token,\n\u001B[32m   1022\u001B[39m         \u001B[38;5;66;03m# Additional options\u001B[39;00m\n\u001B[32m   1023\u001B[39m         local_files_only=local_files_only,\n\u001B[32m   1024\u001B[39m         force_download=force_download,\n\u001B[32m   1025\u001B[39m     )\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1115\u001B[39m, in \u001B[36m_hf_hub_download_to_cache_dir\u001B[39m\u001B[34m(cache_dir, repo_id, filename, repo_type, revision, endpoint, etag_timeout, headers, proxies, token, local_files_only, force_download)\u001B[39m\n\u001B[32m   1114\u001B[39m     \u001B[38;5;66;03m# Otherwise, raise appropriate error\u001B[39;00m\n\u001B[32m-> \u001B[39m\u001B[32m1115\u001B[39m     _raise_on_head_call_error(head_call_error, force_download, local_files_only)\n\u001B[32m   1117\u001B[39m \u001B[38;5;66;03m# From now on, etag, commit_hash, url and size are not None.\u001B[39;00m\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\huggingface_hub\\file_download.py:1646\u001B[39m, in \u001B[36m_raise_on_head_call_error\u001B[39m\u001B[34m(head_call_error, force_download, local_files_only)\u001B[39m\n\u001B[32m   1644\u001B[39m \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m   1645\u001B[39m     \u001B[38;5;66;03m# Otherwise: most likely a connection issue or Hub downtime => let's warn the user\u001B[39;00m\n\u001B[32m-> \u001B[39m\u001B[32m1646\u001B[39m     \u001B[38;5;28;01mraise\u001B[39;00m LocalEntryNotFoundError(\n\u001B[32m   1647\u001B[39m         \u001B[33m\"\u001B[39m\u001B[33mAn error happened while trying to locate the file on the Hub and we cannot find the requested files\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m   1648\u001B[39m         \u001B[33m\"\u001B[39m\u001B[33m in the local cache. Please check your connection and try again or make sure your Internet connection\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m   1649\u001B[39m         \u001B[33m\"\u001B[39m\u001B[33m is on.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m   1650\u001B[39m     ) \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34;01mhead_call_error\u001B[39;00m\n",
      "\u001B[31mLocalEntryNotFoundError\u001B[39m: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001B[31mOSError\u001B[39m                                   Traceback (most recent call last)",
      "\u001B[36mCell\u001B[39m\u001B[36m \u001B[39m\u001B[32mIn[4]\u001B[39m\u001B[32m, line 13\u001B[39m\n\u001B[32m      6\u001B[39m \u001B[38;5;66;03m# Use 4-bit quantization to reduce memory usage\u001B[39;00m\n\u001B[32m      7\u001B[39m quantization_config = BitsAndBytesConfig(\n\u001B[32m      8\u001B[39m     load_in_4bit=\u001B[38;5;28;01mTrue\u001B[39;00m,\n\u001B[32m      9\u001B[39m     bnb_4bit_quant_type=\u001B[33m\"\u001B[39m\u001B[33mnf4\u001B[39m\u001B[33m\"\u001B[39m,\n\u001B[32m     10\u001B[39m     bnb_4bit_compute_dtype=torch.bfloat16,\n\u001B[32m     11\u001B[39m )\n\u001B[32m---> \u001B[39m\u001B[32m13\u001B[39m tokenizer = AutoTokenizer.from_pretrained(model_id)\n\u001B[32m     14\u001B[39m model = AutoModelForCausalLM.from_pretrained(\n\u001B[32m     15\u001B[39m     model_id,\n\u001B[32m     16\u001B[39m     quantization_config=quantization_config,\n\u001B[32m   (...)\u001B[39m\u001B[32m     19\u001B[39m     attn_implementation=\u001B[33m\"\u001B[39m\u001B[33meager\u001B[39m\u001B[33m\"\u001B[39m,\n\u001B[32m     20\u001B[39m )\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\transformers\\models\\auto\\tokenization_auto.py:966\u001B[39m, in \u001B[36mAutoTokenizer.from_pretrained\u001B[39m\u001B[34m(cls, pretrained_model_name_or_path, *inputs, **kwargs)\u001B[39m\n\u001B[32m    964\u001B[39m         config = AutoConfig.for_model(**config_dict)\n\u001B[32m    965\u001B[39m     \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[32m--> \u001B[39m\u001B[32m966\u001B[39m         config = AutoConfig.from_pretrained(\n\u001B[32m    967\u001B[39m             pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs\n\u001B[32m    968\u001B[39m         )\n\u001B[32m    969\u001B[39m config_tokenizer_class = config.tokenizer_class\n\u001B[32m    970\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28mhasattr\u001B[39m(config, \u001B[33m\"\u001B[39m\u001B[33mauto_map\u001B[39m\u001B[33m\"\u001B[39m) \u001B[38;5;129;01mand\u001B[39;00m \u001B[33m\"\u001B[39m\u001B[33mAutoTokenizer\u001B[39m\u001B[33m\"\u001B[39m \u001B[38;5;129;01min\u001B[39;00m config.auto_map:\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\transformers\\models\\auto\\configuration_auto.py:1114\u001B[39m, in \u001B[36mAutoConfig.from_pretrained\u001B[39m\u001B[34m(cls, pretrained_model_name_or_path, **kwargs)\u001B[39m\n\u001B[32m   1111\u001B[39m trust_remote_code = kwargs.pop(\u001B[33m\"\u001B[39m\u001B[33mtrust_remote_code\u001B[39m\u001B[33m\"\u001B[39m, \u001B[38;5;28;01mNone\u001B[39;00m)\n\u001B[32m   1112\u001B[39m code_revision = kwargs.pop(\u001B[33m\"\u001B[39m\u001B[33mcode_revision\u001B[39m\u001B[33m\"\u001B[39m, \u001B[38;5;28;01mNone\u001B[39;00m)\n\u001B[32m-> \u001B[39m\u001B[32m1114\u001B[39m config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)\n\u001B[32m   1115\u001B[39m has_remote_code = \u001B[33m\"\u001B[39m\u001B[33mauto_map\u001B[39m\u001B[33m\"\u001B[39m \u001B[38;5;129;01min\u001B[39;00m config_dict \u001B[38;5;129;01mand\u001B[39;00m \u001B[33m\"\u001B[39m\u001B[33mAutoConfig\u001B[39m\u001B[33m\"\u001B[39m \u001B[38;5;129;01min\u001B[39;00m config_dict[\u001B[33m\"\u001B[39m\u001B[33mauto_map\u001B[39m\u001B[33m\"\u001B[39m]\n\u001B[32m   1116\u001B[39m has_local_code = \u001B[33m\"\u001B[39m\u001B[33mmodel_type\u001B[39m\u001B[33m\"\u001B[39m \u001B[38;5;129;01min\u001B[39;00m config_dict \u001B[38;5;129;01mand\u001B[39;00m config_dict[\u001B[33m\"\u001B[39m\u001B[33mmodel_type\u001B[39m\u001B[33m\"\u001B[39m] \u001B[38;5;129;01min\u001B[39;00m CONFIG_MAPPING\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\transformers\\configuration_utils.py:590\u001B[39m, in \u001B[36mPretrainedConfig.get_config_dict\u001B[39m\u001B[34m(cls, pretrained_model_name_or_path, **kwargs)\u001B[39m\n\u001B[32m    588\u001B[39m original_kwargs = copy.deepcopy(kwargs)\n\u001B[32m    589\u001B[39m \u001B[38;5;66;03m# Get config dict associated with the base config file\u001B[39;00m\n\u001B[32m--> \u001B[39m\u001B[32m590\u001B[39m config_dict, kwargs = \u001B[38;5;28mcls\u001B[39m._get_config_dict(pretrained_model_name_or_path, **kwargs)\n\u001B[32m    591\u001B[39m \u001B[38;5;28;01mif\u001B[39;00m config_dict \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m:\n\u001B[32m    592\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m {}, kwargs\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\transformers\\configuration_utils.py:649\u001B[39m, in \u001B[36mPretrainedConfig._get_config_dict\u001B[39m\u001B[34m(cls, pretrained_model_name_or_path, **kwargs)\u001B[39m\n\u001B[32m    645\u001B[39m configuration_file = kwargs.pop(\u001B[33m\"\u001B[39m\u001B[33m_configuration_file\u001B[39m\u001B[33m\"\u001B[39m, CONFIG_NAME) \u001B[38;5;28;01mif\u001B[39;00m gguf_file \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m \u001B[38;5;28;01melse\u001B[39;00m gguf_file\n\u001B[32m    647\u001B[39m \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[32m    648\u001B[39m     \u001B[38;5;66;03m# Load from local folder or from cache or download from model Hub and cache\u001B[39;00m\n\u001B[32m--> \u001B[39m\u001B[32m649\u001B[39m     resolved_config_file = cached_file(\n\u001B[32m    650\u001B[39m         pretrained_model_name_or_path,\n\u001B[32m    651\u001B[39m         configuration_file,\n\u001B[32m    652\u001B[39m         cache_dir=cache_dir,\n\u001B[32m    653\u001B[39m         force_download=force_download,\n\u001B[32m    654\u001B[39m         proxies=proxies,\n\u001B[32m    655\u001B[39m         resume_download=resume_download,\n\u001B[32m    656\u001B[39m         local_files_only=local_files_only,\n\u001B[32m    657\u001B[39m         token=token,\n\u001B[32m    658\u001B[39m         user_agent=user_agent,\n\u001B[32m    659\u001B[39m         revision=revision,\n\u001B[32m    660\u001B[39m         subfolder=subfolder,\n\u001B[32m    661\u001B[39m         _commit_hash=commit_hash,\n\u001B[32m    662\u001B[39m     )\n\u001B[32m    663\u001B[39m     \u001B[38;5;28;01mif\u001B[39;00m resolved_config_file \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m:\n\u001B[32m    664\u001B[39m         \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m, kwargs\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\transformers\\utils\\hub.py:266\u001B[39m, in \u001B[36mcached_file\u001B[39m\u001B[34m(path_or_repo_id, filename, **kwargs)\u001B[39m\n\u001B[32m    208\u001B[39m \u001B[38;5;28;01mdef\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34mcached_file\u001B[39m(\n\u001B[32m    209\u001B[39m     path_or_repo_id: Union[\u001B[38;5;28mstr\u001B[39m, os.PathLike],\n\u001B[32m    210\u001B[39m     filename: \u001B[38;5;28mstr\u001B[39m,\n\u001B[32m    211\u001B[39m     **kwargs,\n\u001B[32m    212\u001B[39m ) -> Optional[\u001B[38;5;28mstr\u001B[39m]:\n\u001B[32m    213\u001B[39m \u001B[38;5;250m    \u001B[39m\u001B[33;03m\"\"\"\u001B[39;00m\n\u001B[32m    214\u001B[39m \u001B[33;03m    Tries to locate a file in a local folder and repo, downloads and cache it if necessary.\u001B[39;00m\n\u001B[32m    215\u001B[39m \n\u001B[32m   (...)\u001B[39m\u001B[32m    264\u001B[39m \u001B[33;03m    ```\u001B[39;00m\n\u001B[32m    265\u001B[39m \u001B[33;03m    \"\"\"\u001B[39;00m\n\u001B[32m--> \u001B[39m\u001B[32m266\u001B[39m     file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)\n\u001B[32m    267\u001B[39m     file = file[\u001B[32m0\u001B[39m] \u001B[38;5;28;01mif\u001B[39;00m file \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;129;01mnot\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m \u001B[38;5;28;01melse\u001B[39;00m file\n\u001B[32m    268\u001B[39m     \u001B[38;5;28;01mreturn\u001B[39;00m file\n",
      "\u001B[36mFile \u001B[39m\u001B[32m~\\.conda\\envs\\medical-soap-note-generator\\Lib\\site-packages\\transformers\\utils\\hub.py:491\u001B[39m, in \u001B[36mcached_files\u001B[39m\u001B[34m(path_or_repo_id, filenames, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)\u001B[39m\n\u001B[32m    488\u001B[39m     \u001B[38;5;66;03m# Here we only raise if both flags for missing entry and connection errors are True (because it can be raised\u001B[39;00m\n\u001B[32m    489\u001B[39m     \u001B[38;5;66;03m# even when `local_files_only` is True, in which case raising for connections errors only would not make sense)\u001B[39;00m\n\u001B[32m    490\u001B[39m     \u001B[38;5;28;01melif\u001B[39;00m _raise_exceptions_for_missing_entries:\n\u001B[32m--> \u001B[39m\u001B[32m491\u001B[39m         \u001B[38;5;28;01mraise\u001B[39;00m \u001B[38;5;167;01mOSError\u001B[39;00m(\n\u001B[32m    492\u001B[39m             \u001B[33mf\u001B[39m\u001B[33m\"\u001B[39m\u001B[33mWe couldn\u001B[39m\u001B[33m'\u001B[39m\u001B[33mt connect to \u001B[39m\u001B[33m'\u001B[39m\u001B[38;5;132;01m{\u001B[39;00mHUGGINGFACE_CO_RESOLVE_ENDPOINT\u001B[38;5;132;01m}\u001B[39;00m\u001B[33m'\u001B[39m\u001B[33m to load the files, and couldn\u001B[39m\u001B[33m'\u001B[39m\u001B[33mt find them in the\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    493\u001B[39m             \u001B[33mf\u001B[39m\u001B[33m\"\u001B[39m\u001B[33m cached files.\u001B[39m\u001B[38;5;130;01m\\n\u001B[39;00m\u001B[33mCheckout your internet connection or see how to run the library in offline mode at\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    494\u001B[39m             \u001B[33m\"\u001B[39m\u001B[33m \u001B[39m\u001B[33m'\u001B[39m\u001B[33mhttps://huggingface.co/docs/transformers/installation#offline-mode\u001B[39m\u001B[33m'\u001B[39m\u001B[33m.\u001B[39m\u001B[33m\"\u001B[39m\n\u001B[32m    495\u001B[39m         ) \u001B[38;5;28;01mfrom\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[34;01me\u001B[39;00m\n\u001B[32m    496\u001B[39m \u001B[38;5;66;03m# snapshot_download will not raise EntryNotFoundError, but hf_hub_download can. If this is the case, it will be treated\u001B[39;00m\n\u001B[32m    497\u001B[39m \u001B[38;5;66;03m# later on anyway and re-raised if needed\u001B[39;00m\n\u001B[32m    498\u001B[39m \u001B[38;5;28;01melif\u001B[39;00m \u001B[38;5;28misinstance\u001B[39m(e, HTTPError) \u001B[38;5;129;01mand\u001B[39;00m \u001B[38;5;129;01mnot\u001B[39;00m \u001B[38;5;28misinstance\u001B[39m(e, EntryNotFoundError):\n",
      "\u001B[31mOSError\u001B[39m: We couldn't connect to 'https://huggingface.co' to load the files, and couldn't find them in the cached files.\nCheckout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'."
     ]
    }
   ],
   "execution_count": 4
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
